#!/usr/bin/env python3
"""Generate the worker app's language dictionaries from the JSON files in this folder.

Each <code>.json maps the exact English UI text (the key used in tr("…")) to its translation.
Keys missing from a file simply fall back to English in the app. Run after editing any JSON:

    python3 apps/worker/i18n/gen.py

Writes app/src/main/java/com/homehelp/pro/I18n<Code>.kt. The map is split across several
functions so no single JVM method grows past the 64 KB limit.
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'app', 'src', 'main', 'java', 'com', 'homehelp', 'pro')
LANGS = {  # code: (Kotlin val name, file suffix, language name)
    'hi': ('HINDI', 'Hi', 'Hindi'), 'bn': ('BENGALI', 'Bn', 'Bengali'), 'te': ('TELUGU', 'Te', 'Telugu'),
    'mr': ('MARATHI', 'Mr', 'Marathi'), 'ta': ('TAMIL', 'Ta', 'Tamil'), 'gu': ('GUJARATI', 'Gu', 'Gujarati'),
    'kn': ('KANNADA', 'Kn', 'Kannada'), 'ml': ('MALAYALAM', 'Ml', 'Malayalam'), 'or': ('ODIA', 'Or', 'Odia'),
    'pa': ('PUNJABI', 'Pa', 'Punjabi'), 'as': ('ASSAMESE', 'As', 'Assamese'), 'ur': ('URDU', 'Ur', 'Urdu'),
}
CHUNK = 250

def kt(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"').replace('$', '\\$').replace('\n', '\\n') + '"'

def main():
    keys = list(json.load(open(os.path.join(HERE, 'hi.json'), encoding='utf-8')).keys())
    for code, (val, suf, name) in LANGS.items():
        path = os.path.join(HERE, f'{code}.json')
        data = json.load(open(path, encoding='utf-8')) if os.path.exists(path) else {}
        items = [(k, v) for k, v in data.items() if isinstance(v, str) and v.strip()]
        parts = [items[i:i + CHUNK] for i in range(0, len(items), CHUNK)] or [[]]
        fn = val.lower()
        lines = ['package com.homehelp.pro', '', f'// GENERATED by apps/worker/i18n/gen.py from {code}.json — edit the JSON, not this file.',
                 f'/** {name} UI dictionary used by [tr]: English source string -> {name}. Missing keys fall back to English. */',
                 f'internal val {val}: Map<String, String> by lazy {{', f'    HashMap<String, String>({max(16, len(items) * 2)}).apply {{']
        lines += [f'        putAll({fn}Part{i + 1}())' for i in range(len(parts))]
        lines += ['    }', '}', '']
        for i, part in enumerate(parts):
            lines.append(f'private fun {fn}Part{i + 1}(): Map<String, String> = mapOf(')
            lines += [f'    {kt(k)} to {kt(v)},' for k, v in part]
            lines += [')', '']
        open(os.path.join(OUT, f'I18n{suf}.kt'), 'w', encoding='utf-8').write('\n'.join(lines))
        cov = sum(1 for k in keys if data.get(k))
        print(f'{code}: {len(items)} entries, covers {cov}/{len(keys)} source strings')

if __name__ == '__main__':
    sys.exit(main())
