package com.homehelp.pro

// GENERATED by apps/worker/i18n/gen.py from ml.json — edit the JSON, not this file.
/** Malayalam UI dictionary used by [tr]: English source string -> Malayalam. Missing keys fall back to English. */
internal val MALAYALAM: Map<String, String> by lazy {
    HashMap<String, String>(16).apply {
        putAll(malayalamPart1())
    }
}

private fun malayalamPart1(): Map<String, String> = mapOf(
)
