package com.homehelp.pro

// GENERATED by apps/worker/i18n/gen.py from ta.json — edit the JSON, not this file.
/** Tamil UI dictionary used by [tr]: English source string -> Tamil. Missing keys fall back to English. */
internal val TAMIL: Map<String, String> by lazy {
    HashMap<String, String>(16).apply {
        putAll(tamilPart1())
    }
}

private fun tamilPart1(): Map<String, String> = mapOf(
)
