package com.homehelp.pro

// GENERATED by apps/worker/i18n/gen.py from or.json — edit the JSON, not this file.
/** Odia UI dictionary used by [tr]: English source string -> Odia. Missing keys fall back to English. */
internal val ODIA: Map<String, String> by lazy {
    HashMap<String, String>(16).apply {
        putAll(odiaPart1())
    }
}

private fun odiaPart1(): Map<String, String> = mapOf(
)
