package com.homehelp.pro

// GENERATED by apps/worker/i18n/gen.py from gu.json — edit the JSON, not this file.
/** Gujarati UI dictionary used by [tr]: English source string -> Gujarati. Missing keys fall back to English. */
internal val GUJARATI: Map<String, String> by lazy {
    HashMap<String, String>(16).apply {
        putAll(gujaratiPart1())
    }
}

private fun gujaratiPart1(): Map<String, String> = mapOf(
)
