package com.homehelp.pro

// GENERATED by apps/worker/i18n/gen.py from as.json — edit the JSON, not this file.
/** Assamese UI dictionary used by [tr]: English source string -> Assamese. Missing keys fall back to English. */
internal val ASSAMESE: Map<String, String> by lazy {
    HashMap<String, String>(16).apply {
        putAll(assamesePart1())
    }
}

private fun assamesePart1(): Map<String, String> = mapOf(
)
