package com.homehelp.pro

// GENERATED by apps/worker/i18n/gen.py from mr.json — edit the JSON, not this file.
/** Marathi UI dictionary used by [tr]: English source string -> Marathi. Missing keys fall back to English. */
internal val MARATHI: Map<String, String> by lazy {
    HashMap<String, String>(16).apply {
        putAll(marathiPart1())
    }
}

private fun marathiPart1(): Map<String, String> = mapOf(
)
