package com.homehelp.pro

// GENERATED by apps/worker/i18n/gen.py from kn.json — edit the JSON, not this file.
/** Kannada UI dictionary used by [tr]: English source string -> Kannada. Missing keys fall back to English. */
internal val KANNADA: Map<String, String> by lazy {
    HashMap<String, String>(16).apply {
        putAll(kannadaPart1())
    }
}

private fun kannadaPart1(): Map<String, String> = mapOf(
)
