package com.homehelp.pro

// GENERATED by apps/worker/i18n/gen.py from ur.json — edit the JSON, not this file.
/** Urdu UI dictionary used by [tr]: English source string -> Urdu. Missing keys fall back to English. */
internal val URDU: Map<String, String> by lazy {
    HashMap<String, String>(16).apply {
        putAll(urduPart1())
    }
}

private fun urduPart1(): Map<String, String> = mapOf(
)
