package com.homehelp.pro

// GENERATED by apps/worker/i18n/gen.py from te.json — edit the JSON, not this file.
/** Telugu UI dictionary used by [tr]: English source string -> Telugu. Missing keys fall back to English. */
internal val TELUGU: Map<String, String> by lazy {
    HashMap<String, String>(16).apply {
        putAll(teluguPart1())
    }
}

private fun teluguPart1(): Map<String, String> = mapOf(
)
