package com.homehelp.pro

// GENERATED by apps/worker/i18n/gen.py from pa.json — edit the JSON, not this file.
/** Punjabi UI dictionary used by [tr]: English source string -> Punjabi. Missing keys fall back to English. */
internal val PUNJABI: Map<String, String> by lazy {
    HashMap<String, String>(16).apply {
        putAll(punjabiPart1())
    }
}

private fun punjabiPart1(): Map<String, String> = mapOf(
)
