package com.homehelp.pro

// GENERATED by apps/worker/i18n/gen.py from bn.json — edit the JSON, not this file.
/** Bengali UI dictionary used by [tr]: English source string -> Bengali. Missing keys fall back to English. */
internal val BENGALI: Map<String, String> by lazy {
    HashMap<String, String>(16).apply {
        putAll(bengaliPart1())
    }
}

private fun bengaliPart1(): Map<String, String> = mapOf(
)
